# Generated by Django 5.2.17 on 2026-09-04 02:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("leagues", "0001_initial"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("kind", models.CharField(max_length=40)),
                ("rationale", models.TextField()),
                ("recommendation", models.JSONField(default=dict)),
                ("shadow_mode", models.BooleanField(default=True)),
                (
                    "roster_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="leagues.rostersnapshot",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="leagues.fantasyteam"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManagerPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("autopilot_enabled", models.BooleanField(default=False)),
                ("shadow_mode", models.BooleanField(default=True)),
                ("max_weekly_adds", models.PositiveSmallIntegerField(default=0)),
                (
                    "max_faab_per_player",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_faab_per_week",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "minimum_improvement",
                    models.FloatField(
                        default=2, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("trades_require_approval", models.BooleanField(default=True)),
                ("protected_players", models.ManyToManyField(blank=True, to="players.player")),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy",
                        to="leagues.fantasyteam",
                    ),
                ),
            ],
        ),
    ]
