# Generated by Django 5.2.17 on 2026-09-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCache',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fetched_at', models.DateTimeField()),
                ('data', models.JSONField()),
            ],
        ),
    ]
