# Generated by Django 5.2.17 on 2026-09-04 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("espn_id", models.PositiveBigIntegerField()),
                ("season", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("settings", models.JSONField(default=dict)),
                ("scoring_period", models.PositiveSmallIntegerField(default=0)),
                ("matchup_period", models.PositiveSmallIntegerField(default=0)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("espn_id", "season"), name="unique_league_season"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FreeAgentSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("scoring_period", models.PositiveSmallIntegerField()),
                ("captured_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("limit", models.PositiveIntegerField(default=100)),
                ("data", models.JSONField(default=list)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_agent_snapshots",
                        to="leagues.league",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FantasyTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("espn_id", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("owners", models.JSONField(default=list)),
                ("preferences", models.JSONField(blank=True, default=dict)),
                ("waiver_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("transaction_counters", models.JSONField(default=dict)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="leagues.league",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchupSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("espn_id", models.PositiveBigIntegerField()),
                ("scoring_period", models.PositiveSmallIntegerField()),
                ("matchup_period", models.PositiveSmallIntegerField()),
                ("captured_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("data", models.JSONField(default=dict)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchup_snapshots",
                        to="leagues.league",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RosterSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("scoring_period", models.PositiveSmallIntegerField()),
                ("captured_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_snapshots",
                        to="leagues.fantasyteam",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
            },
        ),
        migrations.CreateModel(
            name="RosterSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("lineup_slot_id", models.PositiveSmallIntegerField()),
                ("projected_points", models.FloatField(blank=True, null=True)),
                ("actual_points", models.FloatField(blank=True, null=True)),
                ("injury_status", models.CharField(blank=True, max_length=40)),
                ("eligible_slots", models.JSONField(default=list)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="players.player"
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="leagues.rostersnapshot",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="fantasyteam",
            constraint=models.UniqueConstraint(
                fields=("league", "espn_id"), name="unique_team_league"
            ),
        ),
        migrations.AddConstraint(
            model_name="rosterslot",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "player"), name="unique_roster_player"
            ),
        ),
    ]
