# Generated by Django 5.2.17 on 2026-09-04 04:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLease',
            fields=[
                ('key', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('token', models.UUIDField(null=True)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
