# Generated by Django 5.2.17 on 2026-09-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_synclease'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosterslot',
            name='pro_team_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
