# Generated by Django 5.2.17 on 2026-09-04 14:29

import django.utils.timezone
from django.db import migrations, models


def route_schedule(apps, schema_editor, task_name, previous_name):
    tasks = apps.get_model("django_celery_beat", "PeriodicTask")
    changed = tasks.objects.using(schema_editor.connection.alias).filter(
        name="ESPN shadow sync", task=previous_name,
    ).update(task=task_name)
    if changed:
        apps.get_model("django_celery_beat", "PeriodicTasks").objects.using(
            schema_editor.connection.alias
        ).update_or_create(ident=1, defaults={"last_update": django.utils.timezone.now()})


def forwards(apps, schema_editor):
    route_schedule(apps, schema_editor, "leagues.tasks.schedule_sync", "leagues.tasks.sync_and_recommend")


def backwards(apps, schema_editor):
    route_schedule(apps, schema_editor, "leagues.tasks.sync_and_recommend", "leagues.tasks.schedule_sync")


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_rosterslot_pro_team_id'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRequest',
            fields=[
                ('key', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('token', models.UUIDField(null=True)),
                ('status', models.CharField(default='idle', max_length=12)),
                ('requested_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cooldown_until', models.DateTimeField(default=django.utils.timezone.now)),
                ('decision_id', models.PositiveBigIntegerField(null=True)),
            ],
            options={
                'permissions': [('request_sync', 'Can request a league update')],
            },
        ),
        migrations.RunPython(forwards, backwards),
    ]
