# Generated by Django 5.2.17 on 2026-09-04 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_syncrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espn_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='PENDING', max_length=40)),
                ('scoring_period', models.PositiveSmallIntegerField(default=0)),
                ('process_at', models.DateTimeField(blank=True, null=True)),
                ('observed_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('data', models.JSONField(default=dict)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offers', to='leagues.league')),
                ('proposing_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_trade_offers', to='leagues.fantasyteam')),
            ],
            options={
                'ordering': ['-observed_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('league', 'espn_id'), name='unique_trade_offer')],
            },
        ),
    ]
