# Generated by Django 5.2.17 on 2026-09-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_mcpoauthclient_mcpoauthgrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='schedule',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
