# Generated by Django 5.2.17 on 2026-09-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("espn_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("position_id", models.PositiveSmallIntegerField()),
                ("pro_team_id", models.PositiveSmallIntegerField(default=0)),
                ("eligible_slots", models.JSONField(default=list)),
                ("injury_status", models.CharField(blank=True, max_length=40)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
